name: {{appName}}
description: {{appDescription}}

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  get_it: ^7.7.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  uuid: ^4.4.0
  http: ^1.2.1
  feather_icons: ^1.2.0
  emoji_picker_flutter: 1.6.1
  cached_network_image: ^3.3.1
  rctv: ^0.0.22

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  